spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: javaguides
  exchange:
    name: javaguides_exchange
  routing:
    key: javaguides_routing_key


